# Generated by Django 4.2.29 on 2026-03-17 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_site_alter_user_role_workupdate_task_site_customer_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('worker', 'date')},
        ),
    ]
