# Generated by Django 4.2.29 on 2026-03-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_present',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='slot',
            field=models.CharField(choices=[('early', 'Early Morning (5 AM - 8 AM)'), ('morning', 'Morning (9 AM - 1 PM)'), ('afternoon', 'Afternoon (1 PM - 6 PM)')], default='morning', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('worker', 'date', 'slot')},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status',
        ),
    ]
