# Generated by Django 4.2.29 on 2026-03-19 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='owner_photo',
            field=models.ImageField(blank=True, null=True, upload_to='sites/owners/'),
        ),
        migrations.AddField(
            model_name='site',
            name='site_photo',
            field=models.ImageField(blank=True, null=True, upload_to='sites/photos/'),
        ),
        migrations.AddField(
            model_name='site',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='In Progress', max_length=50),
        ),
        migrations.AlterField(
            model_name='site',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='site',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_site', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='site',
            name='owner_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='site',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
