# Generated by Django 4.2.29 on 2026-03-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_site_created_at_site_owner_photo_site_site_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='location',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Google Maps Link'),
        ),
    ]
