# Generated by Django 4.2.29 on 2026-03-19 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_site_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('family_phone', models.CharField(blank=True, max_length=20, verbose_name='Family Contact Number')),
                ('address', models.TextField(blank=True)),
                ('id_proof', models.ImageField(blank=True, null=True, upload_to='workers/id_proofs/', verbose_name='ID Proof Photo')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='workers/photos/', verbose_name='Worker Photo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
