# Generated by Django 4.2.29 on 2026-03-19 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='worker',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_workers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'worker'}, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.site'),
        ),
    ]
