# Generated by Django 4.2.29 on 2026-03-19 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_task_worker_task_assigned_workers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('attendance', 'Attendance'), ('task', 'Task'), ('site', 'Site'), ('worker', 'Worker'), ('bill', 'Bill'), ('update', 'Work Update'), ('tool', 'Tool'), ('product', 'Product'), ('auth', 'Auth')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
