# Generated by Django 4.2.29 on 2026-03-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_user_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Image URL'),
        ),
    ]
