# Generated by Django 4.2.29 on 2026-03-21 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_product_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
    ]
