# Generated by Django 4.2.29 on 2026-03-22 07:06

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.bill_photo_path),
        ),
        migrations.AlterField(
            model_name='site',
            name='owner_photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.owner_photo_path),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.site_photo_path),
        ),
        migrations.AlterField(
            model_name='tool',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.tool_photo_path),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='id_proof',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.worker_id_proof_path, verbose_name='ID Proof Photo'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.worker_photo_path, verbose_name='Worker Photo'),
        ),
        migrations.AlterField(
            model_name='workupdate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.update_photo_path),
        ),
    ]
