# Generated by Django 4.2.29 on 2026-03-22 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_bill_image_alter_site_owner_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewedUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_updates', to=settings.AUTH_USER_MODEL)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_by', to='core.workupdate')),
            ],
            options={
                'unique_together': {('customer', 'update')},
            },
        ),
    ]
